import Lean
import Batteries.Tactic.Lint

/-! # Unused-export check

Reports non-private declarations of a target Lean module whose
package is not referenced by any other declaration in the
formalization. Run as

  lake exe check_unused_exports [--allowlist <path>] \
    TargetModule LibA LibB ... -- ExeRootA ExeRootB ...

Args before `--` are libraries imported together with the target
into a single environment; args after `--` are executable roots
(each one declares `def main`, so they conflict in a shared
environment and have to be imported one-at-a-time into separate
environments whose references are merged into the global
referenced set).

`--allowlist <path>` points at a JSON file listing exports that
should be exempted (e.g. identifiers referenced only via raw-string
emission or as syntactic placeholders). Each listed name must
exist in the loaded environment, otherwise the check fails — that
keeps the file from going stale.

Compiler-generated auxiliaries (recursors, match equations,
projections, constructors, derived `Repr` helpers) and decls with
macro scopes are exempt — only user-written, non-private `def`s
are required to have a referrer.

Exits non-zero with a list of offenders if any unused exports are
found, zero with a `-- No unused exports in <Target>.` line
otherwise. -/

open Lean Batteries.Tactic.Lint

/-- Prefixes that mark auto-derived typeclass instances. The
    `deriving` clause synthesises `inst*` decls whose body is
    boilerplate; flagging those as unused exports would amount
    to policing language-level features rather than user code. -/
private def autoDerivedInstPrefixes : List String :=
  [ "instRepr", "instInhabited", "instBEq", "instDecidableEq"
  , "instCoe", "instFunctor", "instToString", "instOrd"
  , "instHashable", "instLawful", "instMonad", "instMonadLift"
  , "instApplicative", "instAlternative" ]

/-- Whether a single name component is compiler-generated. -/
private def isAuxComponent (s : String) : Bool :=
  s.startsWith "eq_" ||
  s.startsWith "match_" ||
  s.startsWith "proof_" ||
  s.startsWith "brecOn" ||
  s.startsWith "_sparseCasesOn" ||
  s.startsWith "_flat_" ||
  s.startsWith "_aux_" ||
  s.startsWith "_sizeOf_" ||
  s.endsWith "sizeOf_spec" ||
  s.endsWith "_sunfold" ||
  s == "splitter" ||
  s == "recOn" || s == "casesOn" ||
  s == "noConfusion" || s == "noConfusionType" ||
  s == "toCtorIdx" || s == "ctorIdx" ||
  s == "elim" || s == "below" ||
  s == "ndrec" || s == "ndrecOn" ||
  s == "binductionOn" || s == "rec" ||
  s == "_unsafe_rec" || s == "_unary" ||
  s == "_default" ||
  s == "quot" || s == "formatter" || s == "parenthesizer" ||
  s == "delab" ||
  autoDerivedInstPrefixes.any (fun p => s.startsWith p)

/-- Whether `n` looks like a Lean parser/syntax-extension name
    auto-generated by the `syntax` / `elab_rules` machinery: the
    macro inserts `Lean.Parser.Category.*` entries plus
    syntax-rule names containing literal punctuation rendered
    via French-bracket escapes (`«…»`). Such decls show up in
    `env.constants` even though they are never referenced as
    Lean constants. -/
private def isParserGenName (n : Name) : Bool :=
  let asStr := n.toString
  -- French-bracket-quoted names are syntax-rule literals
  -- (e.g. `«fnExpr_+_»`). Any decl whose printed form contains
  -- one of those brackets is a syntax-extension byproduct.
  asStr.any (fun c => c == '«' || c == '»') ||
  -- Auto-generated parser-category placeholders.
  (`Lean.Parser.Category).isPrefixOf n

/-- Whether `n` is a compiler-generated auxiliary declaration
    (match equational lemmas, sizeof specs, recursor helpers,
    derived `Repr` / `Inhabited` / `BEq` instances, parser
    quotation helpers, …). Checked component-wise so nested
    auxiliaries (e.g. `RustExpr.brecOn_5.go`,
    `DslLint.instReprDiagnostic.repr`) are recognised. -/
private def isAuxDecl (n : Name) : Bool :=
  isParserGenName n ||
  n.components.any
    fun c => match c with
      | .str _ s => isAuxComponent s
      | _ => false

/-- Constant heads of types that signal a decl is plumbed into
    Lean's parser/elaborator/macro infrastructure rather than
    invoked as an ordinary Lean constant. Decls with one of
    these as their type's head (e.g. `def docInterp :
    Lean.ParserDescr := …`) are looked up by Lean at parse /
    elaboration time via attribute extensions, so
    `getUsedConstantsAsSet` cannot see them. -/
private def parserExtensionTypes : List Name :=
  [ `Lean.ParserDescr
  , `Lean.TrailingParserDescr
  , `Lean.Parser.Parser
  , `Lean.Parser.TrailingParser
  , `Lean.Parser.ParserFn
  , `Lean.PrettyPrinter.Formatter
  , `Lean.PrettyPrinter.Parenthesizer
  , `Lean.Macro
  , `Lean.Elab.Term.TermElab
  , `Lean.Elab.Command.CommandElab
  , `Lean.Elab.Tactic.Tactic
  , `Lean.KeyedDeclsAttribute ]

/-- Whether `n`'s declared type's head constant is in
    `parserExtensionTypes`. -/
private def hasParserExtensionType
    (env : Environment) (n : Name) : Bool :=
  match env.find? n with
  | some ci =>
    match ci.type.getAppFn with
    | .const c _ => parserExtensionTypes.contains c
    | _          => false
  | none => false

/-- Result-type heads of function-type-aliased Lean handlers
    (after stripping all `forallE` / `→` binders). `def f :
    Term.TermElab := …` is stored with type unfolded to
    `Syntax → Option Expr → TermElabM Expr`; the head of that
    return is `TermElabM`, which signals attribute-table
    plumbing rather than direct callers. -/
private def parserExtensionReturnHeads : List Name :=
  [ `Lean.Elab.Term.TermElabM
  , `Lean.Elab.Command.CommandElabM
  , `Lean.Elab.Tactic.TacticM
  , `Lean.MacroM ]

/-- True iff `n` is a `def` whose final return type's head
    constant is in `parserExtensionReturnHeads`. -/
private def hasParserExtensionReturnType
    (env : Environment) (n : Name) : Bool :=
  match env.find? n with
  | some ci =>
    match ci.type.getForallBody.getAppFn with
    | .const c _ => parserExtensionReturnHeads.contains c
    | _          => false
  | none => false

/-- The defining module of `n` in `env`, if any. Looks up the
    constant's module index and returns the corresponding entry
    in `env.header.moduleNames`. Returns `none` for decls
    without an assigned module (e.g. shadowed temporaries). -/
private def declModule? (env : Environment) (n : Name) : Option Name := do
  let idx ← env.const2ModIdx[n]?
  env.header.moduleNames[idx]?

/-- True iff `n` is defined in a module whose qualified name
    starts with one of `userRoots`. Crucially, this checks the
    *module* the decl lives in rather than the decl's own root
    component, so `private` decls (whose internal names are
    mangled with a `_private.` prefix) are still classified as
    user code. -/
private def inUserPackage
    (env : Environment) (userRoots : Array Name) (n : Name) : Bool :=
  match declModule? env n with
  | some modName => userRoots.any (·.isPrefixOf modName)
  | none         => false

/-- Accumulate into `acc` the constants referenced by any decl
    in `env` defined in a user-package module. Self-references
    are excluded so a decl referencing only itself doesn't mask
    an unused export. -/
private def addReferencedFrom
    (acc : NameSet) (env : Environment)
    (userRoots : Array Name) : NameSet := Id.run do
  let mut referenced := acc
  for (n, ci) in env.constants.toList do
    unless inUserPackage env userRoots n do continue
    for c in ci.getUsedConstantsAsSet do
      if c != n then referenced := referenced.insert c
  return referenced

/-- All decls in `env` defined in a module of package `target`,
    keyed by *module* rather than name root. Decls with
    namespaces other than `target` (e.g. a `Core/Order.lean` file
    that opens `namespace Lean`) are still captured because the
    defining module is what determines library membership. -/
private def declsInPackage
    (env : Environment) (target : Name) : Array Name :=
  env.constants.fold (init := #[]) fun acc n _ =>
    match declModule? env n with
    | some modName =>
      if target.isPrefixOf modName then acc.push n else acc
    | none => acc

/-- Whether `d` is a user-written, non-private, non-auxiliary
    declaration whose presence as an export should be justified
    by some referrer. -/
private def isCheckableExport
    (env : Environment) (d : Name) : CoreM Bool := do
  if isPrivateName d then return false
  if d.hasMacroScopes then return false
  if env.isConstructor d then return false
  if isAuxDecl d then return false
  if (← isProjectionFn d) then return false
  if hasParserExtensionType env d then return false
  if hasParserExtensionReturnType env d then return false
  -- Definitions only — skip theorems / opaque / axioms /
  -- inductives / quotients (those carry their own meaning even
  -- without callers). The audit targets dead `def`s.
  match env.find? d with
  | some (.defnInfo _) => return true
  | _ => return false

/-- Split `args` at the first `--`. Args before `--` are
    libraries imported together; args after are executable
    roots imported one-at-a-time. -/
private def splitArgs (args : List String)
    : List String × List String :=
  match args.span (· != "--") with
  | (libs, _ :: exes) => (libs, exes)
  | (libs, [])        => (libs, [])

/-- One JSON allowlist entry: the qualified name of a Core
    declaration that is allowed to lack any compile-time
    referrer, paired with a human-readable rationale. -/
private structure Exemption where
  name : String
  reason : String
  deriving Lean.FromJson

/-- Top-level shape of `unused_exports_allowlist.json`. The
    `comment` field is informational; only `exemptions` is
    consumed by the check. -/
private structure Allowlist where
  comment : Option String := none
  exemptions : Array Exemption := #[]
  deriving Lean.FromJson

/-- Parse the JSON allowlist at `path`. -/
private def loadAllowlist
    (path : System.FilePath) : IO (Array Exemption) := do
  let raw ← IO.FS.readFile path
  match Lean.Json.parse raw with
  | .error e =>
    throw <| IO.userError s!"failed to parse {path}: {e}"
  | .ok json =>
    match Lean.fromJson? (α := Allowlist) json with
    | .error e =>
      throw <| IO.userError s!"failed to read {path}: {e}"
    | .ok al => return al.exemptions

/-- Pop a `--key value` pair out of `args` if present. Returns
    the captured value (if any) and the remaining args. -/
private def popFlag (args : List String) (key : String)
    : Option String × List String :=
  let rec go : List String → Option String × List String
    | [] => (none, [])
    | k :: v :: rest =>
      if k == key then (some v, rest)
      else
        let (found, tail) := go (v :: rest)
        (found, k :: tail)
    | [k] => (none, [k])
  go args

unsafe def main (args : List String) : IO UInt32 := do
  let (allowlistArg, rest) := popFlag args "--allowlist"
  let (libs, exes) := splitArgs rest
  match libs with
  | [] =>
    IO.eprintln <|
      "Usage: check_unused_exports [--allowlist <path>] " ++
      "Target Lib1 [Lib2 ...] [-- Exe1 Exe2 ...]"
    return 1
  | target :: otherLibs =>
    let exemptions ← match allowlistArg with
      | some path => loadAllowlist path
      | none      => pure #[]
    let exemptNames : NameSet := exemptions.foldl
      (init := ({} : NameSet)) fun acc e =>
        acc.insert e.name.toName
    let targetMod := target.toName
    let libMods := otherLibs.map String.toName
    let exeMods := exes.map String.toName
    let allLibMods := targetMod :: libMods
    initSearchPath (← findSysroot)
    enableInitializersExecution
    let libImports := allLibMods.map fun m =>
      ({ module := m } : Import)
    let env ← importModules libImports.toArray {}
      (trustLevel := 1024) (loadExts := true)
    let allRoots := ((allLibMods ++ exeMods).map
      Name.getRoot).toArray
    let mut referenced := addReferencedFrom {} env allRoots
    -- Each executable root defines its own `main`, so we can't
    -- import them all into one environment. Process each
    -- separately and merge its references into the global set.
    -- `loadExts := false` here — initializers can only run once
    -- per process, and we only need decl bodies (not extensions)
    -- to walk references with `getUsedConstantsAsSet`.
    for exeMod in exeMods do
      let envExe ← importModules
        #[({ module := exeMod } : Import)] {}
        (trustLevel := 1024) (loadExts := false)
      referenced := addReferencedFrom referenced envExe
        #[exeMod.getRoot]
    -- Validate that every allowlist entry resolves to a real
    -- decl in the target package — stale names should fail loud
    -- rather than silently mask future regressions.
    let mut stale : Array String := #[]
    for e in exemptions do
      let n := e.name.toName
      let found := env.find? n |>.isSome
      let inTarget := match declModule? env n with
        | some modName => targetMod.isPrefixOf modName
        | none         => false
      unless found && inTarget do stale := stale.push e.name
    if !stale.isEmpty then
      IO.eprintln s!"unused-exports allowlist: stale entries:"
      for s in stale do
        IO.eprintln s!"  {s}"
      IO.eprintln <|
        "(name not found, or defined outside the target " ++
        "package — rename or remove from the allowlist)"
      return 1
    let targetDecls := declsInPackage env targetMod
    let ctx : Core.Context :=
      { fileName := "", fileMap := default }
    let state : Core.State := { env }
    let result ← Core.CoreM.toIO (do
      let mut unused : Array Name := #[]
      for d in targetDecls do
        unless ← isCheckableExport env d do continue
        if exemptNames.contains d then continue
        if !referenced.contains d then
          unused := unused.push d
      return unused) ctx state
    let unused := result.fst
    if unused.isEmpty then
      IO.println s!"-- No unused exports in {target}."
      return 0
    IO.eprintln s!"UNUSED EXPORTS in {target}:"
    for d in unused.qsort (·.toString < ·.toString) do
      IO.eprintln s!"  {d}"
    IO.eprintln <| "Either remove the declaration, mark it " ++
      "`private`, or add a referrer in another module " ++
      "(or, if used only via runtime name resolution, add an " ++
      "entry to the allowlist with a justification)."
    return 1
