[book]
authors = ["Zack Grannan"]
language = "en"
multilingual = false
src = "src"
title = "PCG Documentation"

[preprocessor.katex]
after = ["links"]
macros = "macros.txt"

[preprocessor.hypergraph]
command = "node preprocessors/hypergraph.js"

[output.html]
mathjax-support = true
additional-css = ["theme/custom.css"]
additional-js = ["theme/cytoscape.min.js", "theme/hypergraph.js"]
