import Shared.OrderDef
import Lean

open Lean Elab Command Term in

declare_syntax_cat orderFact

/-- A covering relation: `| greater > lesser`. -/
syntax "| " ident " > " ident : orderFact

/-- Define a partial order on a finite enum by listing covering
    relations. Computes the reflexive-transitive closure and
    generates a `le` function, `LE` and `Decidable` instances,
    and an `orderDef : OrderDef` for export.

    Proofs that this defines a partial order, lattice, etc. should
    be written separately using the generated `le` function.

    Example:
    ```
    defOrder Capability where
      | exclusive > read
      | exclusive > write
      | write > none
      | read > none
    ```
-/
syntax "defOrder " ident " where" orderFact* : command

/-- Compute the reflexive-transitive closure of a relation on a
    finite set of elements. -/
private def closureOf
    (elements : List String) (facts : List (String × String))
    : List (String × String) :=
  let refl := elements.map fun e => (e, e)
  let initial := refl ++ facts
  let rec loop (pairs : List (String × String))
      (fuel : Nat) : List (String × String) :=
    match fuel with
    | 0 => pairs
    | fuel' + 1 =>
      let newPairs := pairs.flatMap fun (a, b) =>
        pairs.filterMap fun (c, d) =>
          if b == c && !(pairs.any fun (x, y) => x == a && y == d)
          then some (a, d)
          else none
      if newPairs.isEmpty then pairs
      else loop (pairs ++ newPairs) fuel'
  loop initial elements.length

open Lean Elab Command Term in
elab_rules : command
  | `(defOrder $name:ident where $fs:orderFact*) => do
    -- Parse facts
    let factData ← fs.mapM fun f => match f with
      | `(orderFact| | $g:ident > $l:ident) =>
        pure (toString g.getId, toString l.getId)
      | _ => throwError "invalid order fact"
    let factList := factData.toList

    -- Get the enum constructors from the environment
    let env ← getEnv
    let nameId := name.getId
    let ctorNames := match env.find? nameId with
      | some (.inductInfo val) => val.ctors
      | _ => []
    if ctorNames.isEmpty then
      throwError s!"defOrder: {nameId} is not an inductive type"

    let elements := ctorNames.map fun n => n.getString!

    -- Validate that all fact names refer to valid constructors
    for (g, l) in factList do
      unless elements.contains g do
        throwError s!"defOrder: unknown constructor '{g}'"
      unless elements.contains l do
        throwError s!"defOrder: unknown constructor '{l}'"

    -- Compute closure (≤ direction: swap facts from > to ≤)
    let leFacts := factList.map fun (g, l) => (l, g)
    let closure := closureOf elements leFacts

    -- Build match arms for the le function.
    -- Each arm: `| .ctor1, .ctor2 => true`
    let si := SourceInfo.none
    let mkDotIdent (s : String) : Syntax :=
      Syntax.node si ``Lean.Parser.Term.dotIdent
        #[Syntax.atom si ".", mkIdent (Name.mkSimple s)]
    let mkMatchArm (a b : String) (val : String)
        : Syntax :=
      Syntax.node si ``Lean.Parser.Term.matchAlt
        #[ Syntax.atom si "|"
         , Syntax.node si `null
            #[ Syntax.node si `null
                #[mkDotIdent a, Syntax.atom si ","
                , mkDotIdent b]]
         , Syntax.atom si "=>"
         , mkIdent (Name.mkSimple val)]
    let trueArms := closure.map fun (a, b) =>
      mkMatchArm a b "true"
    let wildArm := Syntax.node si ``Lean.Parser.Term.matchAlt
      #[ Syntax.atom si "|"
       , Syntax.node si `null
          #[Syntax.node si `null
              #[ Syntax.node si ``Lean.Parser.Term.hole
                  #[Syntax.atom si "_"]
               , Syntax.atom si ","
               , Syntax.node si ``Lean.Parser.Term.hole
                  #[Syntax.atom si "_"]]]
       , Syntax.atom si "=>"
       , mkIdent (Name.mkSimple "false")]
    let allArms := trueArms ++ [wildArm]
    let matchAlts : Syntax := Syntax.node si
      ``Lean.Parser.Term.matchAlts
      #[Syntax.node si `null allArms.toArray]
    let funExpr : TSyntax `term := ⟨Syntax.node si
      ``Lean.Parser.Term.fun
      #[Syntax.atom si "fun", matchAlts]⟩

    -- Generate all definitions with fully qualified names
    -- (avoids hygiene issues with namespace-scoped identifiers)
    let leId := mkIdent (nameId ++ `le)
    let leCmd ← `(command|
      /-- Decidable ordering generated by `defOrder`. -/
      def $leId : $name → $name → Bool := $funExpr)
    elabCommand leCmd

    -- LE instance
    elabCommand (← `(command|
      instance : LE $name where
        le a b := $leId a b = true))

    -- Decidable LE instance
    elabCommand (← `(command|
      instance (a b : $name) :
          Decidable (a ≤ b) :=
        inferInstanceAs (Decidable ($leId a b = true))))

    -- Generate orderDef for export
    let factExprs ← factList.toArray.mapM fun (g, l) => do
      let gs : TSyntax `term := quote g
      let ls : TSyntax `term := quote l
      `({ greater := $gs, lesser := $ls : OrderFact })
    let closureExprs ← closure.toArray.mapM fun (a, b) => do
      let as_ : TSyntax `term := quote a
      let bs : TSyntax `term := quote b
      `(($as_, $bs))
    let elemExprs ← elements.toArray.mapM fun e => do
      let es : TSyntax `term := quote e
      pure es
    let nameStr : TSyntax `term :=
      quote (toString nameId)
    let factList' ← `([$[$factExprs],*])
    let closureList ← `([$[$closureExprs],*])
    let elemList ← `([$[$elemExprs],*])
    let orderDefId := mkIdent (nameId ++ `orderDef)
    elabCommand (← `(command|
      /-- Order metadata for export and presentation. -/
      def $orderDefId : OrderDef :=
        { enumName := $nameStr
          elements := $elemList
          facts := $factList'
          closure := $closureList }))
